In [79]:
import sys
!{sys.executable} -m pip install pandas numpy matplotlib seaborn scikit-learn jinja2

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.5.2)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.11.1)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.9.0)
Collecting jinja2
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/raghavsahab1gmail.com/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /Users/raghavsahab1gmail.com/Library/Python/3.14/lib/python/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Collecting MarkupSafe>=2.0 (from jinja2)
  Downloading markupsafe-3.0.3-cp314-cp314-macosx_10_13_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: cloudpickle>=3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in /Users/raghavsahab1gmail.com/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp314-cp314-macosx_10_13_x86_64.whl (11 kB)
Installing collected packages: MarkupSafe, jinja2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [jinja2]2m1/2 [jinja2]
Successfully installed MarkupSafe-3.0.3 jinja2-3.1.6

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
plt.style.use("ggplot")

In [35]:
df =pd.read_csv("email.csv")

In [36]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [37]:
df

            Category                                            Message
0                ham  Go until jurong point, crazy.. Available only ...
1                ham                      Ok lar... Joking wif u oni...
2               spam  Free entry in 2 a wkly comp to win FA Cup fina...
3                ham  U dun say so early hor... U c already then say...
4                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5568             ham               Will ü b going to esplanade fr home?
5569             ham  Pity, * was in mood for that. So...any other s...
5570             ham  The guy did some bitching but I acted like i'd...
5571             ham                         Rofl. Its true to its name
5572  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]

In [38]:
df.tail(1)

            Category          Message
5572  {"mode":"full"  isActive:false}

In [39]:
df["Category"].value_counts()

Category
ham               4825
spam               747
{"mode":"full"       1
Name: count, dtype: int64

In [40]:
df = df.iloc[:-1]

In [41]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [42]:
df.shape

(5572, 2)

In [43]:
df.dtypes

Category    str
Message     str
dtype: object

In [44]:
df.isnull().sum().sum()

np.int64(0)

In [45]:
df.duplicated().sum()

np.int64(415)

In [46]:
df.drop_duplicates(inplace=True)

In [47]:
df["Category"].value_counts()

Category
ham     4516
spam     641
Name: count, dtype: int64

In [48]:
df["Message_Length"] = df["Message"].apply(len)

In [49]:
df.head()

  Category                                            Message  Message_Length
0      ham  Go until jurong point, crazy.. Available only ...             111
1      ham                      Ok lar... Joking wif u oni...              29
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...             155
3      ham  U dun say so early hor... U c already then say...              49
4      ham  Nah I don't think he goes to usf, he lives aro...              61

In [50]:
df.groupby("Category")["Message_Length"].mean()

Category
ham      70.869353
spam    137.118565
Name: Message_Length, dtype: float64

In [51]:
df["Word_Count"] = df["Message"].apply(lambda x: len(x.split()))

In [52]:
df.head()

,Category,Message,Message_Length,Word_Count
0,ham,"Go until jurong point, crazy.. Available only ...",111,20
1,ham,Ok lar... Joking wif u oni...,29,6
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,155,28
3,ham,U dun say so early hor... U c already then say...,49,11
4,ham,"Nah I don't think he goes to usf, he lives aro...",61,13

In [53]:
df.groupby("Category")["Word_Count"].mean()

Category
ham     14.239814
spam    23.659906
Name: Word_Count, dtype: float64

In [54]:
df.nsmallest(10, "Message_Length")

     Category Message  Message_Length  Word_Count
1925      ham      Ok               2           1
3376      ham      :)               2           1
261       ham     Yup               3           1
1612      ham     645               3           1
2182      ham     Ok.               3           1
287       ham    Ok..               4           1
2602      ham    Okie               4           1
5173      ham    U 2.               4           2
1273      ham   Ok...               5           1
4293      ham   G.W.R               5           1

In [55]:
df.nlargest(10, "Message_Length")

,Category,Message,Message_Length,Word_Count
1085,ham,For me the love should start with attraction.i...,910,171
1863,ham,The last thing i ever wanted to do was hurt yo...,790,162
2434,ham,Indians r poor but India is not a poor country...,629,109
1579,ham,How to Make a girl Happy? It's not at all diff...,611,103
2158,ham,Sad story of a Man - Last week was my b'day. M...,588,125
2380,ham,"Good evening Sir, hope you are having a nice d...",482,98
3017,ham,"&lt;#&gt; is fast approaching. So, Wish u a v...",461,66
1513,ham,"Hey sweet, I was wondering when you had a mome...",458,95
2370,ham,A Boy loved a gal. He propsd bt she didnt mind...,446,96
2408,ham,Solve d Case : A Man Was Found Murdered On &l...,444,71

In [56]:
df["Category"] = df["Category"].map({"ham": 0, "spam": 1})

In [57]:
df.head()

,Category,Message,Message_Length,Word_Count
0,0,"Go until jurong point, crazy.. Available only ...",111,20
1,0,Ok lar... Joking wif u oni...,29,6
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,28
3,0,U dun say so early hor... U c already then say...,49,11
4,0,"Nah I don't think he goes to usf, he lives aro...",61,13

In [58]:
import warnings
warnings.filterwarnings("ignore")

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X=df["Message"]

In [61]:
y=df["Category"]

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify= y)

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=5000,
    ngram_range=(1, 2)
)

In [64]:
X_train_tfidf = tfidf.fit_transform(X_train)

In [65]:
X_test_tfidf = tfidf.transform(X_test)

In [69]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.model_selection import RandomizedSearchCV

In [72]:
models = {
    "Naive Bayes": (MultinomialNB(), {
        "alpha": [0.1, 0.5, 1, 2, 5]
    }),
    "Logistic Regression": (LogisticRegression(
        class_weight="balanced", 
        max_iter=1000
    ), {
        "C" : [0.01, 0.1, 1, 10, 100]
    }),
    "Linear SVM": (LinearSVC(
        class_weight="balanced",
    ), {
        "C" : [0.01, 0.1, 1, 10]
    }),
    "Random Forest": (RandomForestClassifier(
        class_weight="balanced"
    ), {
        "n_estimators" : [100,200,300],
        "max_depth" : [10, 20, None],
        "min_samples_split" : [2, 5, 10]
    }),
    "KNN": (KNeighborsClassifier(), {
        "n_neighbors" : [3, 5, 7, 9],
    }),
    "Decision Tree": (DecisionTreeClassifier(
        class_weight="balanced"
    ), {
        "max_depth" : [5,10,20,None],
        "min_samples_split" : [2,5,10]
    }),
    "Gradient Boosting": (GradientBoostingClassifier(), {
        "n_estimators" : [100,200],
        "learning_rate" : [0.01, 0.05, 0.1],
        "max_depth" : [3,5]
    })
}

In [73]:
results = [ ]

best_models = {}

for name, (model, params) in models.items():

    search = RandomizedSearchCV(
        estimator= model,
        param_distributions= params,
        n_iter= 10,
        scoring= "f1",
        n_jobs= -1,
    )

    search.fit(X_train_tfidf, y_train)

    best_model = search.best_estimator_

    best_models[name] = best_model

    predictions = best_model.predict(X_test_tfidf)

    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)

    try:
        auc = roc_auc_score(y_test, best_model.decision_function(X_test_tfidf))
    except:
        try:
            auc = roc_auc_score(
                y_test, best_model.predict_proba(X_test_tfidf)[:, 1]
            )
        except:
            auc = np.nan

    results.append({
        "Model": name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "ROC AUC": auc,
        "Best Params": search.best_params_
    })

In [74]:
results

[{'Model': 'Naive Bayes',
  'Accuracy': 0.9844961240310077,
  'Precision': 0.9827586206896551,
  'Recall': 0.890625,
  'F1 Score': 0.9344262295081968,
  'ROC AUC': 0.9896380669247787,
  'Best Params': {'alpha': 0.1}},
 {'Model': 'Logistic Regression',
  'Accuracy': 0.9883720930232558,
  'Precision': 0.967741935483871,
  'Recall': 0.9375,
  'F1 Score': 0.9523809523809523,
  'ROC AUC': 0.9849108130530972,
  'Best Params': {'C': 100}},
 {'Model': 'Linear SVM',
  'Accuracy': 0.9854651162790697,
  'Precision': 0.9669421487603306,
  'Recall': 0.9140625,
  'F1 Score': 0.9397590361445783,
  'ROC AUC': 0.9886571833517699,
  'Best Params': {'C': 1}},
 {'Model': 'Random Forest',
  'Accuracy': 0.9806201550387597,
  'Precision': 0.9426229508196722,
  'Recall': 0.8984375,
  'F1 Score': 0.92,
  'ROC AUC': 0.9860818238384955,
  'Best Params': {'n_estimators': 100,
   'min_samples_split': 5,
   'max_depth': None}},
 {'Model': 'KNN',
  'Accuracy': 0.9321705426356589,
  'Precision': 1.0,
  'Recall': 0.453125,
  'F1 Score': 0.6236559139784946,
  'ROC AUC': 0.7911538993362832,
  'Best Params': {'n_neighbors': 3}},
 {'Model': 'Decision Tree',
  'Accuracy': 0.9476744186046512,
  'Precision': 0.7720588235294118,
  'Recall': 0.8203125,
  'F1 Score': 0.7954545454545454,
  'ROC AUC': 0.8954818860619469,
  'Best Params': {'min_samples_split': 2, 'max_depth': None}},
 {'Model': 'Gradient Boosting',
  'Accuracy': 0.9728682170542635,
  'Precision': 0.9716981132075472,
  'Recall': 0.8046875,
  'F1 Score': 0.8803418803418803,
  'ROC AUC': 0.9718654936393805,
  'Best Params': {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.1}}]

In [81]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by = ["F1 Score", "ROC AUC"], 
    ascending= False
)

In [82]:
results_df

,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC,Best Params
1,Logistic Regression,0.988372,0.967742,0.937500,0.952381,0.984911,{'C': 100}
2,Linear SVM,0.985465,0.966942,0.914062,0.939759,0.988657,{'C': 1}
0,Naive Bayes,0.984496,0.982759,0.890625,0.934426,0.989638,{'alpha': 0.1}
3,Random Forest,0.980620,0.942623,0.898438,0.920000,0.986082,"{'n_estimators': 100, 'min_samples_split': 5, ..."
6,Gradient Boosting,0.972868,0.971698,0.804688,0.880342,0.971865,"{'n_estimators': 200, 'max_depth': 5, 'learnin..."
5,Decision Tree,0.947674,0.772059,0.820312,0.795455,0.895482,"{'min_samples_split': 2, 'max_depth': None}"
4,KNN,0.932171,1.000000,0.453125,0.623656,0.791154,{'n_neighbors': 3}

In [83]:
results_df.style.background_gradient(
    cmap = "Greens",
    subset = ["Accuracy", "Precision", "Recall", "F1 Score", "ROC AUC"]
)

In [84]:
results_df.reset_index(inplace=True)

In [85]:
results_df

,index,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC,Best Params
0,1,Logistic Regression,0.988372,0.967742,0.937500,0.952381,0.984911,{'C': 100}
1,2,Linear SVM,0.985465,0.966942,0.914062,0.939759,0.988657,{'C': 1}
2,0,Naive Bayes,0.984496,0.982759,0.890625,0.934426,0.989638,{'alpha': 0.1}
3,3,Random Forest,0.980620,0.942623,0.898438,0.920000,0.986082,"{'n_estimators': 100, 'min_samples_split': 5, ..."
4,6,Gradient Boosting,0.972868,0.971698,0.804688,0.880342,0.971865,"{'n_estimators': 200, 'max_depth': 5, 'learnin..."
5,5,Decision Tree,0.947674,0.772059,0.820312,0.795455,0.895482,"{'min_samples_split': 2, 'max_depth': None}"
6,4,KNN,0.932171,1.000000,0.453125,0.623656,0.791154,{'n_neighbors': 3}

In [86]:
results_df.drop(columns="index", inplace=True)

In [87]:
results_df

,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC,Best Params
0,Logistic Regression,0.988372,0.967742,0.937500,0.952381,0.984911,{'C': 100}
1,Linear SVM,0.985465,0.966942,0.914062,0.939759,0.988657,{'C': 1}
2,Naive Bayes,0.984496,0.982759,0.890625,0.934426,0.989638,{'alpha': 0.1}
3,Random Forest,0.980620,0.942623,0.898438,0.920000,0.986082,"{'n_estimators': 100, 'min_samples_split': 5, ..."
4,Gradient Boosting,0.972868,0.971698,0.804688,0.880342,0.971865,"{'n_estimators': 200, 'max_depth': 5, 'learnin..."
5,Decision Tree,0.947674,0.772059,0.820312,0.795455,0.895482,"{'min_samples_split': 2, 'max_depth': None}"
6,KNN,0.932171,1.000000,0.453125,0.623656,0.791154,{'n_neighbors': 3}

In [88]:
best_model_name = results_df.iloc[0]["Model"]

In [89]:
best_model_name

'Logistic Regression'

In [90]:
best_model = best_models[best_model_name]

In [91]:
best_model

LogisticRegression(C=100, class_weight='balanced', max_iter=1000)

In [93]:
emails = [

    "Congratulations! You've won a free iPhone. Click here now.",

    "Hey, are we still meeting tomorrow at 10 AM?",

    "URGENT! Claim your $1000 Walmart gift card today."
]

emails_vectorized = tfidf.transform(emails)

predictions = best_model.predict(emails_vectorized)


for email, prediction in zip(emails, predictions):
    lable = "Spam" if prediction == 1 else "Ham"

    print(lable, ":", email)

Spam : Congratulations! You've won a free iPhone. Click here now.
Ham : Hey, are we still meeting tomorrow at 10 AM?
Spam : URGENT! Claim your $1000 Walmart gift card today.

In [94]:
import pickle 

with open("spam_classifier.pkl", "wb") as file:
    pickle.dump(best_model, file)

In [95]:
with open("tfidf_vectorizer.pkl", "wb") as file:
    pickle.dump(tfidf, file)

print("Success")

Success

In [96]:
with open("spam_classifier.pkl", "rb") as file:
    loaded_model = pickle.load(file)

with open("tfidf_vectorizer.pkl", "rb") as file:
    loaded_vectorizer = pickle.load(file)